import common from "../services/common.js";
import rates from "../services/rates.js"
const list = async (req, res, next) => {
    const body = req.body;
    let result = { json: {} };
    try {
        const packedItems = await common.pack(body.items);
        result = { status: 200, json: Object.assign(await rates.rate(body, packedItems, req.query), { firstAppraised: parseInt(req.query.firstAppraised), lastAppraised: parseInt(req.query.lastAppraised) }) };
    } catch (error) {
        console.log(error);
        result = { status: 500, json: { error } }
    }
    // const packedItems = {
    //     "packages": [
    //         {
    //             "name": "22\" x 22\"\" x 10\"\" (32 ECT)\"",
    //             "width": 22,
    //             "height": 9,
    //             "length": 22,
    //             "maxWeight": 30,
    //             "cubic": 4356,
    //             "type": "Box",
    //             "foldingStorageForTheItems": "regular",
    //             "rates": [
    //                 {
    //                     "id": "rate_bf35ac6feed94887867cb552ec1d736a",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:19Z",
    //                     "updated_at": "2023-09-01T02:56:19Z",
    //                     "mode": "test",
    //                     "service": "Express",
    //                     "carrier": "USPS",
    //                     "rate": "102.15",
    //                     "currency": "USD",
    //                     "retail_rate": "112.90",
    //                     "retail_currency": "USD",
    //                     "list_rate": "102.15",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": null,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": null,
    //                     "shipment_id": "shp_5ec9b935bff94a8ca427d31b45bb8a62",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_244e790af3c7471d8d18b162de345331",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:19Z",
    //                     "updated_at": "2023-09-01T02:56:19Z",
    //                     "mode": "test",
    //                     "service": "Priority",
    //                     "carrier": "USPS",
    //                     "rate": "50.15",
    //                     "currency": "USD",
    //                     "retail_rate": "56.00",
    //                     "retail_currency": "USD",
    //                     "list_rate": "50.15",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 1,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 1,
    //                     "shipment_id": "shp_5ec9b935bff94a8ca427d31b45bb8a62",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_5c172e7a163a475d88da7566d6fb4fbf",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:19Z",
    //                     "updated_at": "2023-09-01T02:56:19Z",
    //                     "mode": "test",
    //                     "service": "GroundAdvantage",
    //                     "carrier": "USPS",
    //                     "rate": "38.96",
    //                     "currency": "USD",
    //                     "retail_rate": "45.15",
    //                     "retail_currency": "USD",
    //                     "list_rate": "38.96",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 2,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 2,
    //                     "shipment_id": "shp_5ec9b935bff94a8ca427d31b45bb8a62",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_ceca9a7a0c1d4331a40d59be8e4d83eb",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:19Z",
    //                     "updated_at": "2023-09-01T02:56:19Z",
    //                     "mode": "test",
    //                     "service": "First",
    //                     "carrier": "USPS",
    //                     "rate": "38.96",
    //                     "currency": "USD",
    //                     "retail_rate": "45.15",
    //                     "retail_currency": "USD",
    //                     "list_rate": "38.96",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 2,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 2,
    //                     "shipment_id": "shp_5ec9b935bff94a8ca427d31b45bb8a62",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_bfd49bc3d7eb4edda6d8c21e70a97285",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:19Z",
    //                     "updated_at": "2023-09-01T02:56:19Z",
    //                     "mode": "test",
    //                     "service": "Ground",
    //                     "carrier": "UPSDAP",
    //                     "rate": "16.33",
    //                     "currency": "USD",
    //                     "retail_rate": "25.65",
    //                     "retail_currency": "USD",
    //                     "list_rate": "27.65",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 1,
    //                     "delivery_date": "2023-09-05T23:00:00Z",
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 1,
    //                     "shipment_id": "shp_5ec9b935bff94a8ca427d31b45bb8a62",
    //                     "carrier_account_id": "ca_daa6d901f3104f46b9d0d7c84bd7fe4c"
    //                 },
    //                 {
    //                     "id": "rate_03b1f67115594d9f877cad3eecbd2615",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:19Z",
    //                     "updated_at": "2023-09-01T02:56:19Z",
    //                     "mode": "test",
    //                     "service": "GROUND_HOME_DELIVERY",
    //                     "carrier": "FedEx",
    //                     "rate": "10.37",
    //                     "currency": "USD",
    //                     "retail_rate": null,
    //                     "retail_currency": null,
    //                     "list_rate": "29.46",
    //                     "list_currency": "USD",
    //                     "billing_type": "carrier",
    //                     "delivery_days": 1,
    //                     "delivery_date": "2023-09-02T23:59:00Z",
    //                     "delivery_date_guaranteed": true,
    //                     "est_delivery_days": 1,
    //                     "shipment_id": "shp_5ec9b935bff94a8ca427d31b45bb8a62",
    //                     "carrier_account_id": "ca_2f56b199237a4a5cb33cfacddd57187d"
    //                 },
    //                 {
    //                     "id": "rate_e92891840b9a4a55b4430fe040923fe0",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:19Z",
    //                     "updated_at": "2023-09-01T02:56:19Z",
    //                     "mode": "test",
    //                     "service": "FEDEX_2_DAY",
    //                     "carrier": "FedEx",
    //                     "rate": "26.32",
    //                     "currency": "USD",
    //                     "retail_rate": null,
    //                     "retail_currency": null,
    //                     "list_rate": "81.22",
    //                     "list_currency": "USD",
    //                     "billing_type": "carrier",
    //                     "delivery_days": 5,
    //                     "delivery_date": "2023-09-06T20:00:00Z",
    //                     "delivery_date_guaranteed": true,
    //                     "est_delivery_days": 5,
    //                     "shipment_id": "shp_5ec9b935bff94a8ca427d31b45bb8a62",
    //                     "carrier_account_id": "ca_2f56b199237a4a5cb33cfacddd57187d"
    //                 }
    //             ]
    //         },
    //         {
    //             "name": "40 x 18 x 8 (32 ECT)",
    //             "width": 18,
    //             "height": 7,
    //             "length": 40,
    //             "maxWeight": 30,
    //             "cubic": 5040,
    //             "type": "Box",
    //             "foldingStorageForTheItems": "foldedByWidth",
    //             "rates": [
    //                 {
    //                     "id": "rate_994e772a79fa40bdbbb359240d31f9e8",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:21Z",
    //                     "updated_at": "2023-09-01T02:56:21Z",
    //                     "mode": "test",
    //                     "service": "Express",
    //                     "carrier": "USPS",
    //                     "rate": "126.65",
    //                     "currency": "USD",
    //                     "retail_rate": "138.55",
    //                     "retail_currency": "USD",
    //                     "list_rate": "126.65",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": null,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": null,
    //                     "shipment_id": "shp_328fc80b68f24121bcbf4250971c66de",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_d1e8841a94464bb78a42febb58bd78e0",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:21Z",
    //                     "updated_at": "2023-09-01T02:56:21Z",
    //                     "mode": "test",
    //                     "service": "Priority",
    //                     "carrier": "USPS",
    //                     "rate": "68.67",
    //                     "currency": "USD",
    //                     "retail_rate": "74.25",
    //                     "retail_currency": "USD",
    //                     "list_rate": "68.67",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 1,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 1,
    //                     "shipment_id": "shp_328fc80b68f24121bcbf4250971c66de",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_0649eeb30cba494a80d0a3fac3bdf768",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:21Z",
    //                     "updated_at": "2023-09-01T02:56:21Z",
    //                     "mode": "test",
    //                     "service": "GroundAdvantage",
    //                     "carrier": "USPS",
    //                     "rate": "49.01",
    //                     "currency": "USD",
    //                     "retail_rate": "56.05",
    //                     "retail_currency": "USD",
    //                     "list_rate": "49.01",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 2,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 2,
    //                     "shipment_id": "shp_328fc80b68f24121bcbf4250971c66de",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_12722afe1471445ba0eb82a99e399b27",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:21Z",
    //                     "updated_at": "2023-09-01T02:56:21Z",
    //                     "mode": "test",
    //                     "service": "First",
    //                     "carrier": "USPS",
    //                     "rate": "49.01",
    //                     "currency": "USD",
    //                     "retail_rate": "56.05",
    //                     "retail_currency": "USD",
    //                     "list_rate": "49.01",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 2,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 2,
    //                     "shipment_id": "shp_328fc80b68f24121bcbf4250971c66de",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_54e2030d2c994f26b80cf1457fd75d94",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:21Z",
    //                     "updated_at": "2023-09-01T02:56:21Z",
    //                     "mode": "test",
    //                     "service": "Ground",
    //                     "carrier": "UPSDAP",
    //                     "rate": "17.49",
    //                     "currency": "USD",
    //                     "retail_rate": "29.16",
    //                     "retail_currency": "USD",
    //                     "list_rate": "29.01",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 1,
    //                     "delivery_date": "2023-09-05T23:00:00Z",
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 1,
    //                     "shipment_id": "shp_328fc80b68f24121bcbf4250971c66de",
    //                     "carrier_account_id": "ca_daa6d901f3104f46b9d0d7c84bd7fe4c"
    //                 },
    //                 {
    //                     "id": "rate_e95d6ddef3de481aa7c4bba3b2e60d65",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:21Z",
    //                     "updated_at": "2023-09-01T02:56:21Z",
    //                     "mode": "test",
    //                     "service": "GROUND_HOME_DELIVERY",
    //                     "carrier": "FedEx",
    //                     "rate": "11.20",
    //                     "currency": "USD",
    //                     "retail_rate": null,
    //                     "retail_currency": null,
    //                     "list_rate": "30.90",
    //                     "list_currency": "USD",
    //                     "billing_type": "carrier",
    //                     "delivery_days": 1,
    //                     "delivery_date": "2023-09-02T23:59:00Z",
    //                     "delivery_date_guaranteed": true,
    //                     "est_delivery_days": 1,
    //                     "shipment_id": "shp_328fc80b68f24121bcbf4250971c66de",
    //                     "carrier_account_id": "ca_2f56b199237a4a5cb33cfacddd57187d"
    //                 },
    //                 {
    //                     "id": "rate_b06c8ab4408246dd820ae720adbdb1e1",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:21Z",
    //                     "updated_at": "2023-09-01T02:56:21Z",
    //                     "mode": "test",
    //                     "service": "FEDEX_2_DAY",
    //                     "carrier": "FedEx",
    //                     "rate": "27.85",
    //                     "currency": "USD",
    //                     "retail_rate": null,
    //                     "retail_currency": null,
    //                     "list_rate": "94.48",
    //                     "list_currency": "USD",
    //                     "billing_type": "carrier",
    //                     "delivery_days": 5,
    //                     "delivery_date": "2023-09-06T20:00:00Z",
    //                     "delivery_date_guaranteed": true,
    //                     "est_delivery_days": 5,
    //                     "shipment_id": "shp_328fc80b68f24121bcbf4250971c66de",
    //                     "carrier_account_id": "ca_2f56b199237a4a5cb33cfacddd57187d"
    //                 }
    //             ]
    //         },
    //         {
    //             "name": "40 x 18 x 8 (32 ECT)",
    //             "width": 18,
    //             "height": 7,
    //             "length": 40,
    //             "maxWeight": 30,
    //             "cubic": 5040,
    //             "type": "Box",
    //             "foldingStorageForTheItems": "foldedByLength",
    //             "rates": [
    //                 {
    //                     "id": "rate_61298dafb5ab48908c7db7bd681a8fe7",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:23Z",
    //                     "updated_at": "2023-09-01T02:56:23Z",
    //                     "mode": "test",
    //                     "service": "Express",
    //                     "carrier": "USPS",
    //                     "rate": "126.65",
    //                     "currency": "USD",
    //                     "retail_rate": "138.55",
    //                     "retail_currency": "USD",
    //                     "list_rate": "126.65",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": null,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": null,
    //                     "shipment_id": "shp_485db2925c5d48d78d64ac0294aa0a9d",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_c2e9069a40974558b9e5e195dbbacb31",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:23Z",
    //                     "updated_at": "2023-09-01T02:56:23Z",
    //                     "mode": "test",
    //                     "service": "Priority",
    //                     "carrier": "USPS",
    //                     "rate": "68.67",
    //                     "currency": "USD",
    //                     "retail_rate": "74.25",
    //                     "retail_currency": "USD",
    //                     "list_rate": "68.67",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 1,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 1,
    //                     "shipment_id": "shp_485db2925c5d48d78d64ac0294aa0a9d",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_956710a823c2498b9451163051ec0107",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:23Z",
    //                     "updated_at": "2023-09-01T02:56:23Z",
    //                     "mode": "test",
    //                     "service": "GroundAdvantage",
    //                     "carrier": "USPS",
    //                     "rate": "49.01",
    //                     "currency": "USD",
    //                     "retail_rate": "56.05",
    //                     "retail_currency": "USD",
    //                     "list_rate": "49.01",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 2,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 2,
    //                     "shipment_id": "shp_485db2925c5d48d78d64ac0294aa0a9d",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_c19c8e9f8bcc42cc96926b662d1c622c",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:23Z",
    //                     "updated_at": "2023-09-01T02:56:23Z",
    //                     "mode": "test",
    //                     "service": "First",
    //                     "carrier": "USPS",
    //                     "rate": "49.01",
    //                     "currency": "USD",
    //                     "retail_rate": "56.05",
    //                     "retail_currency": "USD",
    //                     "list_rate": "49.01",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 2,
    //                     "delivery_date": null,
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 2,
    //                     "shipment_id": "shp_485db2925c5d48d78d64ac0294aa0a9d",
    //                     "carrier_account_id": "ca_b927401ea7a542f393b51cbd817070b0"
    //                 },
    //                 {
    //                     "id": "rate_72be34ef9b1f42b48b9d753160d48a9b",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:23Z",
    //                     "updated_at": "2023-09-01T02:56:23Z",
    //                     "mode": "test",
    //                     "service": "Ground",
    //                     "carrier": "UPSDAP",
    //                     "rate": "17.49",
    //                     "currency": "USD",
    //                     "retail_rate": "29.16",
    //                     "retail_currency": "USD",
    //                     "list_rate": "29.01",
    //                     "list_currency": "USD",
    //                     "billing_type": "easypost",
    //                     "delivery_days": 1,
    //                     "delivery_date": "2023-09-05T23:00:00Z",
    //                     "delivery_date_guaranteed": false,
    //                     "est_delivery_days": 1,
    //                     "shipment_id": "shp_485db2925c5d48d78d64ac0294aa0a9d",
    //                     "carrier_account_id": "ca_daa6d901f3104f46b9d0d7c84bd7fe4c"
    //                 },
    //                 {
    //                     "id": "rate_ec9fd355516a4134bc56a0b091eed313",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:23Z",
    //                     "updated_at": "2023-09-01T02:56:23Z",
    //                     "mode": "test",
    //                     "service": "GROUND_HOME_DELIVERY",
    //                     "carrier": "FedEx",
    //                     "rate": "11.20",
    //                     "currency": "USD",
    //                     "retail_rate": null,
    //                     "retail_currency": null,
    //                     "list_rate": "30.90",
    //                     "list_currency": "USD",
    //                     "billing_type": "carrier",
    //                     "delivery_days": 1,
    //                     "delivery_date": "2023-09-02T23:59:00Z",
    //                     "delivery_date_guaranteed": true,
    //                     "est_delivery_days": 1,
    //                     "shipment_id": "shp_485db2925c5d48d78d64ac0294aa0a9d",
    //                     "carrier_account_id": "ca_2f56b199237a4a5cb33cfacddd57187d"
    //                 },
    //                 {
    //                     "id": "rate_0c202cb5dd704ff091c64496340b1543",
    //                     "object": "Rate",
    //                     "created_at": "2023-09-01T02:56:23Z",
    //                     "updated_at": "2023-09-01T02:56:23Z",
    //                     "mode": "test",
    //                     "service": "FEDEX_2_DAY",
    //                     "carrier": "FedEx",
    //                     "rate": "27.85",
    //                     "currency": "USD",
    //                     "retail_rate": null,
    //                     "retail_currency": null,
    //                     "list_rate": "94.48",
    //                     "list_currency": "USD",
    //                     "billing_type": "carrier",
    //                     "delivery_days": 5,
    //                     "delivery_date": "2023-09-06T20:00:00Z",
    //                     "delivery_date_guaranteed": true,
    //                     "est_delivery_days": 5,
    //                     "shipment_id": "shp_485db2925c5d48d78d64ac0294aa0a9d",
    //                     "carrier_account_id": "ca_2f56b199237a4a5cb33cfacddd57187d"
    //                 }
    //             ]
    //         },
    //         {
    //             "name": "36 x 18 x 12 (32 ECT)",
    //             "width": 18,
    //             "height": 11,
    //             "length": 36,
    //             "maxWeight": 30,
    //             "cubic": 7128,
    //             "type": "Box",
    //             "foldingStorageForTheItems": "regular"
    //         },
    //         {
    //             "name": "36 x 18 x 12 (32 ECT)",
    //             "width": 18,
    //             "height": 11,
    //             "length": 36,
    //             "maxWeight": 30,
    //             "cubic": 7128,
    //             "type": "Box",
    //             "foldingStorageForTheItems": "foldedByWidth"
    //         },
    //         {
    //             "name": "36 x 18 x 12 (32 ECT)",
    //             "width": 18,
    //             "height": 11,
    //             "length": 36,
    //             "maxWeight": 30,
    //             "cubic": 7128,
    //             "type": "Box",
    //             "foldingStorageForTheItems": "foldedByLength"
    //         }
    //     ],
    //     "items": [
    //         {
    //             "id": "recHSbJD06mqsis7C",
    //             "sku": "GR82062-BKWHT-2XL",
    //             "weight": 21.3,
    //             "length": 17,
    //             "width": 12,
    //             "height": 2,
    //             "foldable": true,
    //             "boxesOnly": false,
    //             "keepVertical": false
    //         },
    //         {
    //             "id": "recpTlIWMepQfbfwK",
    //             "sku": "CLI010-BKWHT-SM",
    //             "weight": 0.4,
    //             "length": 8,
    //             "width": 7,
    //             "height": 5,
    //             "foldable": false,
    //             "boxesOnly": true,
    //             "keepVertical": true
    //         },
    //         {
    //             "id": "recpTlIWMepQfbfwK",
    //             "sku": "CLI010-BKWHT-SM",
    //             "weight": 0.4,
    //             "length": 8,
    //             "width": 7,
    //             "height": 5,
    //             "foldable": false,
    //             "boxesOnly": true,
    //             "keepVertical": true
    //         },
    //         {
    //             "id": "recpTlIWMepQfbfwK",
    //             "sku": "CLI010-BKWHT-SM",
    //             "weight": 0.4,
    //             "length": 8,
    //             "width": 7,
    //             "height": 5,
    //             "foldable": false,
    //             "boxesOnly": true,
    //             "keepVertical": true
    //         },
    //         {
    //             "id": "recpTlIWMepQfbfwK",
    //             "sku": "CLI010-BKWHT-SM",
    //             "weight": 0.4,
    //             "length": 8,
    //             "width": 7,
    //             "height": 5,
    //             "foldable": false,
    //             "boxesOnly": true,
    //             "keepVertical": true
    //         },
    //         {
    //             "id": "recpTlIWMepQfbfwK",
    //             "sku": "CLI010-BKWHT-SM",
    //             "weight": 0.4,
    //             "length": 8,
    //             "width": 7,
    //             "height": 5,
    //             "foldable": false,
    //             "boxesOnly": true,
    //             "keepVertical": true
    //         },
    //         {
    //             "id": "recpTlIWMepQfbfwK",
    //             "sku": "CLI010-BKWHT-SM",
    //             "weight": 0.4,
    //             "length": 8,
    //             "width": 7,
    //             "height": 5,
    //             "foldable": false,
    //             "boxesOnly": true,
    //             "keepVertical": true
    //         },
    //         {
    //             "id": "recpTlIWMepQfbfwK",
    //             "sku": "CLI010-BKWHT-SM",
    //             "weight": 0.4,
    //             "length": 8,
    //             "width": 7,
    //             "height": 5,
    //             "foldable": false,
    //             "boxesOnly": true,
    //             "keepVertical": true
    //         },
    //         {
    //             "id": "recpTlIWMepQfbfwK",
    //             "sku": "CLI010-BKWHT-SM",
    //             "weight": 0.4,
    //             "length": 8,
    //             "width": 7,
    //             "height": 5,
    //             "foldable": false,
    //             "boxesOnly": true,
    //             "keepVertical": true
    //         },
    //         {
    //             "id": "recpTlIWMepQfbfwK",
    //             "sku": "CLI010-BKWHT-SM",
    //             "weight": 0.4,
    //             "length": 8,
    //             "width": 7,
    //             "height": 5,
    //             "foldable": false,
    //             "boxesOnly": true,
    //             "keepVertical": true
    //         },
    //         {
    //             "id": "recpTlIWMepQfbfwK",
    //             "sku": "CLI010-BKWHT-SM",
    //             "weight": 0.4,
    //             "length": 8,
    //             "width": 7,
    //             "height": 5,
    //             "foldable": false,
    //             "boxesOnly": true,
    //             "keepVertical": true
    //         }
    //     ]
    // }
    res.status(result.status);
    res.json(result.json);
}

export default { list }